services:
  app:
    container_name: app
    build: .
    network_mode: host
    depends_on:
      - collector

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
     - 3000:3000
    depends_on:
      - collector
      - app
    networks:
      - grafana

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command: [ "--config.file=/etc/prometheus/prometheus.yaml" ]
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml
    networks:
      - grafana

  collector:
    image: otel/opentelemetry-collector-contrib
    container_name: collector
    command: [ "--config=/etc/collector.yaml"]
    volumes:
      - ./config/opentelemetry/otel-collector-config.yaml:/etc/collector.yaml
    ports:
      - "8888:8888" # Prometheus metrics exposed by the collector
      - "8889:8889" # Prometheus exporter metrics
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP HTTP receiver
    depends_on:
      - prometheus
    networks:
      - grafana

networks:
  grafana: