networks:
  grafana:

services:
  app:
    container_name: app
    build: .
    network_mode: host
    depends_on:
      - collector

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    volumes:
      - ./config/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    ports:
     - 3000:3000
    depends_on:
      - collector
      - app
    networks:
      - grafana

  collector:
    image: otel/opentelemetry-collector-contrib
    container_name: collector
    command: [ "--config=/etc/collector.yaml" ]
    ports:
      - 8888:8888 # Collector health metrics
      - 8889:8889 # Application metrics
      - 4317:4317 # GRPC receiver
      - 4318:4318 # HTTP receiver
    volumes:
      - ./config/opentelemetry/otel-collector-config.yaml:/etc/collector.yaml
    depends_on:
      - tempo
    networks:
      - grafana
    
  tempo_init:
    image: &tempoImage grafana/tempo:latest
    user: root
    entrypoint: 
      - "chown"
      - "10001:10001"
      - "/var/tempo_data"
    volumes:
      - ./config/tempo/data:/var/tempo

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./config/prometheus/prometheus.yaml:/etc/prometheus.yaml
    networks:
      - grafana

  tempo:
    image: *tempoImage
    container_name: tempo
    command: [ "--config.file=/etc/tempo.yaml", "--storage.trace.backend=local", "--distributor.log-received-spans.enabled" ]
    volumes:
      - ./config/tempo/tempo.yaml:/etc/tempo.yaml
      - ./config/tempo/data:/var/tempo
    ports:
      - 3200:3200
    networks:
      - grafana
    depends_on:
      - tempo_init
  
  loki:
    image: grafana/loki
    ports:
      - 3100:3100
    networks:
      - grafana