{
 "title": "Host Resource Usage",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg without(cpu) (irate(node_cpu_seconds_total{job=\"node\", instance=\"localhost:9100\", mode!=\"idle\"}[1m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=\"localhost:9100\", job=\"node\"} - node_memory_MemFree_bytes{instance=\"localhost:9100\", job=\"node\"} - node_memory_Cached_bytes{instance=\"localhost:9100\", job=\"node\"} - node_memory_Buffers_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "Used"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{job=\"node\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} receive"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{job=\"node\",instance=\"localhost:9100\"}[5m])",
     "legendFormat": "{{device}} transmit"
    }
   ]
  },
  {
   "title": "Used Space on Disk",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{instance=\"localhost:9100\", job=\"node\", device!~\"/dev/loop.*\", device!~\"tmpfs | nsfs\", device!=\"gvfsd-fuse\"} - node_filesystem_avail_bytes{instance=\"localhost:9100\", job=\"node\"}",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{instance=\"localhost:9100\",job=\"node\",device!~\"/dev/loop.*\",device!~\"tmpfs | nsfs\",device!=\"gvfsd_fuse\"}",
     "legendFormat": "{{device}}"
    }
   ]
  }
 ]
}